### PR TITLE
remove line 12 and add line 1

### PR DESCRIPTION
**Pull request by saeidnahali**

### CODE REVIEW

**Comment by pakizehjam** [comment]
I do not like to print at this position.

**Comment by pakizehjam** [comment]
I want to print the result at the end of the program.

**Comment by saeidnahali** [comment]
I started to add another print line. I will be work on your code as soon as possible. sorry

**Comment by pakizehjam** [comment]
please put the print at the end of the program.

**Comment by saeidnahali** [comment]
I create new pull request and I code to give you new way to solve your code

**Pull request closed without merging**
